teleop:
  linear_control:
    type: topic
    message_type: geometry_msgs/Twist                     # 消息类型
    topic_name: /velocity_control_node/velocity_control   # 接收手柄信号的Topic
    deadman_buttons: [6]                                  # 安全键（Deadman button），手柄LT按钮
    axis_mappings:
      -
        axis: 0           # 左摇杆纵轴
        target: linear.x  # 前进、倒退
        scale: 0.2        # 速度比例（0.5 意味着，最小速度为-0.5，最大为0.5
      -
        axis: 2           # 右摇杆横轴
        target: linear.y  # 左右平移
        scale: 0.2        # 速度比例（0.5 意味着，最小速度为-0.5，最大为0.5
      -
        axis: 1           # 左摇杆横轴
        target: angular.z # 左右旋转
        scale: 1          # 速度比例（1.0 意味着，最小速度为-1.0，最大为1.0
  angular_control:
    type: topic
    message_type: geometry_msgs/Twist                     # 消息类型
    topic_name: /velocity_control_node/velocity_control   # 接收手柄信号的Topic
    deadman_buttons: [7]                                  # 安全键（Deadman button），手柄RT按钮
    axis_mappings:
      -
        axis: 0           # 左摇杆纵轴
        target: linear.x  # 前进、倒退
        scale: 0.5        # 速度比例（0.5 意味着，最小速度为-0.5，最大为0.5
      -
        axis: 2           # 右摇杆横轴
        target: linear.y  # 左右平移
        scale: 0.5        # 速度比例（0.5 意味着，最小速度为-0.5，最大为0.5
      -
        axis: 1           # 左摇杆横轴
        target: angular.z # 左右旋转
        scale: 1          # 速度比例（1.0 意味着，最小速度为-1.0，最大为1.0

  change_none:
    type: action
    action_name: /charge_station_server_node/change_tool
    action_goal:
      tool: 'empty'
    buttons: [2] # A

  change_gripper:
    type: action
    action_name: /charge_station_server_node/change_tool
    action_goal:
      tool: 'charger'
    buttons: [3] # X

  change_charger:
    type: action
    action_name: /charge_station_server_node/change_tool
    action_goal:
      tool: 'gripper'
    buttons: [1] # B

  set_charge:
    type: action
    action_name: /charge_station_server_node/charge
    action_goal:
      charge: true
    buttons: [5] # RB

  set_uncharge:
    type: action
    action_name: /charge_station_server_node/charge
    action_goal:
      charge: false
    buttons: [4] # LB